# Generated by Django 4.1.7 on 2023-03-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_rename_date_post_created_post_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='created',
        ),
    ]
