# Generated by Django 4.1.7 on 2023-03-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
