# Generated by Django 4.0.3 on 2023-04-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_is_payed_post_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
